version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\wwwroot\DSCC_CW_8402_UI_publish
  - source: \deploy-scripts\deletewebsite.ps1
    destination: c:\temp
  - source: \deploy-scripts\installwebsite.ps1
    destination: c:\temp
  - source: \deploy-scripts\deletewebsite.bat
    destination: c:\temp
  - source: \deploy-scripts\installwebsite.bat
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: \deploy-scripts\deletewebsite.bat
      timeout: 180
  AfterInstall:
    - location: \deploy-scripts\installwebsite.bat
      timeout: 180